package com.example.linteacher.api.pojo.teacherdata.profile

import java.io.Serializable

data class TeacherProfileResponse(
    val eMail: String="",
    val introduce: Any?=null,
    var sex: Any?=null,
    val tch106PaySalary: Any?=null,
    val tch107PaySalary: Any?=null,
    var tchAboriginal: Any?=null,
    val tchAdminiJob: Any?=null,
    val tchAppointDate: Any?=null,
    var tchBirthday: Any?=null,
    val tchCertificateNumber: Any?=null,
    val tchCertificateRank: Any?=null,
    val tchCoeDepartment: Any?=null,
    val tchComplyLaw: Any?=null,
    var tchCountry: Any?=null,
    var tchDepartment: Any?=null,
    var tchDiploma: Any?=null,
    val tchEstablishment: Any?=null,
    val tchEvaNumber: Any?=null,
    var tchExpertise: Any?=null,
    val tchFiestAssistant: Any?=null,
    val tchFullPartPosition: Any?=null,
    val tchFullTime: Any?=null,
    val tchHireNumber: Any?=null,
    val tchHureDate: Any?=null,
    var tchIdNumberI: Any?=null,
    val tchIdNumberP: Any?=null,
    val tchIdNumberR: Any?=null,
    val tchIdType: Any?=null,
    var tchIsAboriginal: Any?=null,
    val tchKind: Any?=null,
    val tchKindDepartment: Any?=null,
    val tchKindIndustry: Any?=null,
    val tchMainDepartment: Any?=null,
    var tchName: String?=null,
    var tchNameEN: Any?=null,
    val tchNumber: Int=0,
    val tchOriginalUnit: Any?=null,
    val tchPartAdmini: Any?=null,
    val tchPicUrl: String?="",
    val tchReinstateDate: Any?=null,
    val tchResignDate: Any?=null,
    val tchRireRank: Any?=null,
    val tchRireYear: Any?=null,
    val tchScePurpose: Any?=null,
    val tchSceWhemain_ther: Any?=null,
    val tchSchDate: Any?=null,
    var tchSchool: Any?=null,
    var tchSchoolType: Any?=null,
    val tchSecUnit: Any?=null,
    val tchSemester: Int=0,
    val tchSixtyFive: Any?=null,
    val tchState: Any?=null,
    val tchStopDate: Any?=null,
    val tchTow: Any="",
    val tchTwoFour: Any="",
    val tchType: Any="",
    val tchValidationStatus: Any="",
    val tchYear: Int=0,
    val tchmain_licenseNumber: Any=""
):Serializable{

}