package com.example.linteacher.api.pojo.teacherdata.profile

import java.io.Serializable

data class TeacherProfileResponse(
    val eMail: String="",
    var introduce: String?=null,
    var sex: Any?=null,
    val tch106PaySalary: Any?=null,
    var tch107PaySalary: Any?=null,
    var tchAboriginal: Any?=null,
    var tchAdminiJob: Any?=null,
    var tchAppointDate: Any?=null,
    var tchBirthday: Any?=null,
    var tchCertificateNumber: Any?=null,
    var tchCertificateRank: Any?=null,
    var tchCoeDepartment: Any?=null,
    var tchComplyLaw: Any?=null,
    var tchCountry: Any?=null,
    var tchDepartment: Any?=null,
    var tchDiploma: Any?=null,
    var tchEstablishment: Any?=null,
    var tchEvaNumber: Any?=null,
    var tchExpertise: Any?=null,
    var tchFiestAssistant: Any?=null,
    var tchFullPartPosition: Any?=null,
    var tchFullTime: Any?=null,
    var tchHireNumber: Any?=null,
    var tchHureDate: Any?=null,
    var tchIdNumberI: Any?=null,
    val tchIdNumberP: Any?=null,
    val tchIdNumberR: Any?=null,
    val tchIdType: Any?=null,
    var tchIsAboriginal: Any?=null,
    var tchKind: Any?=null,
    var tchKindDepartment: Any?=null,
    var tchKindIndustry: Any?=null,
    var tchMainDepartment: Any?=null,
    var tchName: String?=null,
    var tchNameEN: Any?=null,
    val tchNumber: Int=0,
    var tchOriginalUnit: Any?=null,
    var tchPartAdmini: Any?=null,
    var tchPicUrl: String?="",
    var tchReinstateDate: Any?=null,
    var tchResignDate: Any?=null,
    var tchRireRank: Any?=null,
    var tchRireYear: Any?=null,
    var tchScePurpose: Any?=null,
    var tchSceWhemain_ther: Any?=null,
    var tchSchDate: Any?=null,
    var tchSchool: Any?=null,
    var tchSchoolType: Any?=null,
    var tchSecUnit: Any?=null,
    val tchSemester: Int=0,
    val tchSixtyFive: Any?=null,
    var tchState: Any?=null,
    var tchStopDate: Any?=null,
    val tchTow: Any?="",
    var tchTwoFour: Any?="",
    var tchType: Any?="",
    val tchValidationStatus: Any?="",
    val tchYear: Int=0,
    var tchmain_licenseNumber: Any?=""
):Serializable{

}